services:
  backend:
    build: .
    container_name: store-manager-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: database
      MYSQL_PASSWORD: password
      MYSQL_USERNAME: root
      DATABASE_URL: jdbc:mysql://database:3306/storeManager?createDatabaseIfNotExist=true

    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql
    container_name: store-manager-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5